version: "3.3"
networks:
  jenkins:
    driver: bridge
volumes: 
  jenkins-docker-certs:
  jenkins-data:
services:
  jenkins-blueocean:
    image: jenkinsci/blueocean
    depends_on:
      - jenkins-docker
    networks: 
      - jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    environment: 
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes: 
      - "jenkins-docker-certs:/certs/client:ro"
      - "jenkins-data:/var/jenkins_home"
  jenkins-docker:
    image: docker:dind
    privileged: true
    networks:
      jenkins:
        aliases: 
          - docker
    ports:
      - "2376:2376"
    environment: 
      - DOCKER_TLS_CERTDIR=/certs
    volumes: 
      - "jenkins-docker-certs:/certs/client"
      - "jenkins-data:/var/jenkins_home"
